### SOlving System of LInear Equations
$$X_1 + X_2 − X_3 + 3X_4 = 4$$
$$3X_1 − X_2 + X_3 + 2X_4 = 2$$
$$−2X_1 + 0X_2 + X_3 + X_4 = 2$$
$$X_1 + 3X_2 − X_3 − X_4 = −4$$


In [2]:
import numpy as np


Express the syst of equations as:
$$A.X = B$$

where A = [ \\
   1  1  -1 3 \\
   2  3  p \\
]

In [4]:
# Define A matrix (coeff)
A = np.matrix([
  [1, 1, -1, 3 ],
    [3, -1, 1, 2 ],
    [-2, 0, 1, 1 ],
    [1, 3, -1, -1 ],
])
print(A)

# Define B matrix (value/outcome)
B = np.matrix([
  [4,2,2,-4 ]
]).reshape(4,1)
print(B)

[[ 1  1 -1  3]
 [ 3 -1  1  2]
 [-2  0  1  1]
 [ 1  3 -1 -1]]
[[ 4]
 [ 2]
 [ 2]
 [-4]]


In [6]:
X = np.linalg.inv(A) @ B
print(X)

[[-0.48275862]
 [-0.82758621]
 [-0.55172414]
 [ 1.5862069 ]]


In [8]:
E = B - (A@X)
print(E)

[[-8.8817842e-16]
 [ 0.0000000e+00]
 [ 0.0000000e+00]
 [ 0.0000000e+00]]


In [9]:
E_sq = np.square(E)
print(E_sq)

[[7.88860905e-31]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]


In [11]:
MSE = np.average(E_sq)

In [13]:
RMSE = np.sqrt(MSE)
print("%f"%RMSE)

0.000000
