In [1]:
import numpy as np

In [2]:
# X = (A_inverse) @ B
'''
X = [
  x2,
  x3
]
'''

A = np.matrix([
    [2, 3],
    [3, 1]
])
print(A)

B = np.matrix([
    [8],
    [5]
])
print(B)

[[2 3]
 [3 1]]
[[8]
 [5]]


In [3]:
# Inverse of A
A_inv = np.linalg.inv(A)
print(A_inv)

[[-0.14285714  0.42857143]
 [ 0.42857143 -0.28571429]]


In [4]:
# Validate correct invserse
print(A @ A_inv)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00]]


In [6]:
# solve X
X = A_inv @ B
print(X)

[[1.]
 [2.]]


In [18]:
# Error calculation
B_predicted = A @ X
E = B - B_predicted


print(E)

[[8.88178420e-16]
 [1.77635684e-15]]


In [12]:
E_sq = np.square(E)

In [14]:
MSE = np.average(E_sq)

In [16]:
RMSE = np.sqrt(MSE)
print('{:f}'.format(MSE))

0.000000
