### SOlving System of LInear Equations
$$X_1 + X_2 + X_3 = 2$$
$$2X_1 − X_2 + X_3 = 5$$
$$−X_1 + 2X_2 + 2X_3 = 1$$
$$3X_1 − X_3 = 1$$
$$X_2 − 3X_3 = −7$$


In [2]:
import numpy as np


Express the syst of equations as:
$$A.X = B$$
Where,
$ \mathbf{A} =
\begin{bmatrix}
      1 & 1 & 1 \\
      2 & -1 & 1 \\
      -1 & 2 & 2 \\
      3 & 0 & -1 \\
      0 & 1 & -3  \\
\end{bmatrix}$
, and
$\mathbf{B} =
\begin{bmatrix}
      2  \\
      5  \\
      1 \\
      1 \\
      -7  \\
\end{bmatrix}$


In [6]:
# Define A matrix (coeff)
A = np.matrix([
  [1, 1,  1],
  [2, -1, 1],
  [-1, 2, 2],
  [3, 0, -1],
  [0, 1, -3],
]).reshape(5,3)
print(f"A={A}\n")

# Define B matrix (value/outcome)
B = np.matrix([
  [2,5,1,1,-7]
]).reshape(5,1)
print(f"B={B}\n")

A=[[ 1  1  1]
 [ 2 -1  1]
 [-1  2  2]
 [ 3  0 -1]
 [ 0  1 -3]]

B=[[ 2]
 [ 5]
 [ 1]
 [ 1]
 [-7]]



### Treating non-Square matrix *A*
*Note:* We can't compute the inverse of a non-square matrix (A).
Thus, we multiply the A_transpose on both sides of:
$$A.X = B$$
to get:
$$A^T.A.X = A^T.B$$
or
$$A_{new}.X = B_{new}$$
where, $A_{new} = A^T.A$, and is a square matrix.

In [8]:
# DOES NOT WORK
# X = np.linalg.inv(A) @ B
# print(X)

In [16]:
A_new = A.transpose() @ A
print(A_new)

B_new = A.transpose() @ B
print(B_new)

X = np.linalg.inv(A_new) @ B_new
print(f"\nX={X}\n")

[[15 -3 -2]
 [-3  7  1]
 [-2  1 16]]
[[14]
 [-8]
 [29]]

X=[[ 1.]
 [-1.]
 [ 2.]]



### The solution found is an approximation.
Recall that a matrix operation is also a projection.

The $A^T$ multiplied to $A$ has shrunken its dimentions from $5 \times 3$ to $3 \times 3$, and that is sort of a lossy compression (just like a shadow of a 3-D object is only a 2-D manifestation, which loses the 3D information).

Let's compute the MSE/RMSE by substituting the solution $X$ into the equations.

In [34]:
E = B - (A@X)
print(f"{E}")

[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 4.44089210e-16]
 [-1.11022302e-15]
 [-8.88178420e-16]]


In [35]:
E_sq = np.square(E)
print(E_sq)

[[0.00000000e+00]
 [0.00000000e+00]
 [1.97215226e-31]
 [1.23259516e-30]
 [7.88860905e-31]]


In [36]:
MSE = np.average(E_sq)

In [37]:
RMSE = np.sqrt(MSE)
print("%f"%RMSE)

0.000000


### Conclusion
Given the RMSE is almost 0.0, the solution obtained satisfies all the equations to the maximum possible extent.

However, this may not be true always (depending on the system of equations given in the question). For instance, the system below is not consistent (RMSE will be high). Find out as an exercise!


$$X_1 + X_2 = 3$$
$$2X_1 − X_2 = 3$$
$$3X_1 + X_2 = 7$$
$$X_1 − 2X_2 = 0$$
$$X_1 + X_2 = 10$$
