In [1]:
import numpy as np


In [5]:
M1 = np.matrix([i for i in range(1,13)]).reshape(3,4)
print(M1)
M2 = np.ones((2,3))
print(M2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# dot product
A_0_0 = np.dot(M2[0,:], M1[:,0])