# Mastering Python functions and Libraries
### (c) Sujeet Banerjee

`math` is Python's built-in module for basic scalar mathematics, `numpy` is the standard for fast array and matrix operations, `sympy` allows for symbolic mathematics (like calculus), and `matplotlib.pyplot` is our primary visualization tool. We also import specific functions from `scipy` and `sklearn` for optimization and machine learning.

### 1. Essential Imports
We begin by importing the core mathematical and data science libraries.

In [2]:
# =================================================================
# MODULE: AI & ML LIBRARY STARTER TEMPLATE
# =================================================================

# --- 1. CORE IMPORTS ---
import math as m
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
from scipy.optimize import minimize
from sklearn.linear_model import LinearRegression

from math import pi as pi

### 2. Built-in `math` Library Functions
Python's standard `math` library provides classical mathematical functions. Note that these functions (like `sqrt`, `exp`, `log`, `sin`) generally only accept a **single scalar value** at a time. Passing a list or array to them directly will cause a `TypeError`.

In [14]:
# "Math" LIbrary Only 1 value at a time
print (m.sqrt(16) ) # Square root
print ( m.exp (1)) # Euler ’s number (e)
print ( m.log (10) ) # Natural logarithm
print()
print ( m.sin (m.pi / 2) ) # sin
print ( m.sin (m.pi / 6) ) # sin
print ( m.exp (0) ) # e to the power zero!



4.0
2.718281828459045
2.302585092994046

1.0
0.49999999999999994
1.0


### 3. Function Chaining
You can pass the output of one function directly as the input to another. This is known as **chaining**. Here, we compute the square root, find its ceiling, and then take the sine of that result, seamlessly stringing operations together.

In [7]:
x = 5
u = m.sqrt(x)
print(u)

y = m.ceil(u)
z = m.sin(y)
print(y)

# Chaining of functions!
print(m.ceil(m.sqrt(5)))
m.sin(m.ceil(m.sqrt(x)))

2.23606797749979
3
3


0.1411200080598672

### 4. Applying Math Functions to Collections (The Long Way)
If we want to apply a standard `math` function to multiple items in a list, we cannot simply pass the list itself to the function. We are forced to use a **`for` loop** to process each item individually. This logic is valid, but can become slow on massive datasets.

In [15]:
numbers = [4, 16, 9, 144, 121, 232, 2323, 23232, 23223, 23232323, 23]

# Calculate and print square-root of every number!
# Do it every time - copy-paste 100 times!
print(m.sqrt(4))
print(m.sqrt(16))
print(m.sqrt(144))
print(m.sqrt(121))
print(m.sqrt(9))
# print(...) copy for the remaining numbers!

print()

# Alternative: use for-loop
for num in numbers:
    print(m.sqrt(num))

2.0
4.0
12.0
11.0
3.0

2.0
4.0
3.0
12.0
11.0
15.231546211727817
48.19751030914356
152.4204710660612
152.39094461286078
4819.992012441515
4.795831523312719


### 5. Vectorization with NumPy
This is where `numpy` unleashes its true power! Using NumPy, we can apply `np.sqrt()` to an entire sequence at once. This mechanism is called **vectorization**. It eliminates slow Python `for` loops and computes the results highly efficiently using low-level C code.

In [20]:
# Use Numpy, without the need of 'for-loop'

# numbers = np.array([4, 16, 9, 144, 121, 232, 2323, 23232, 23223, 23232323, 23])
# No loop

np.sqrt(numbers)


array([2.00000000e+00, 4.00000000e+00, 3.00000000e+00, 1.20000000e+01,
       1.10000000e+01, 1.52315462e+01, 4.81975103e+01, 1.52420471e+02,
       1.52390945e+02, 4.81999201e+03, 4.79583152e+00])

### 6. Vectorized Trigonometry
Just like `sqrt`, NumPy provides a vectorized version for trigonometric functions. Notice how `np.sin()` accepts an entire collection of angles simultaneously and returns an array of their corresponding sines.

In [9]:
# Limitation of math.sin() function - can only
# take single value at a time:

# m.sin([m.pi / 2,
#        m.pi / 6,
#         m.pi / 3
#        ])

# Use numpy.sin(...) function - can take multiple values
# at a time:
np.sin([m.pi / 2,
       m.pi / 6,
        m.pi / 3
       ])

array([1.       , 0.5      , 0.8660254])

### 7. Element-wise Operations and Aggregations
NumPy allows arrays to behave mathematically like single values. Adding or multiplying two arrays performs the operation **element-wise** (index 0 with index 0, index 1 with index 1, etc.). Additionally, methods like `.sum()` instantly aggregate array contents, vastly reducing code clutter.

In [38]:
list1 = np.array([10, 20, 30, 40, 50, 99, 999, 8])
list2 = np.array([1, 2, 3, 4, 5, 2, 4, 6])

# No for-loop required
print(list1 + list2)
print(list1 * list2)
print(list1.shape)

print("----------")
# Earlier
sum = 0
for num in list1:
    sum += num
print(sum)
print("----------")
# Now, using numpy:
print(list1.sum())

[  11   22   33   44   55  101 1003   14]
[  10   40   90  160  250  198 3996   48]
(8,)
----------
1256
----------
1256


### 8. Matrices and Dimensionality Errors
NumPy provides matrix structures (via `np.matrix` or 2D `np.array`). While matrix addition works element-by-element, **Matrix Multiplication** (using the `@` operator) strictly requires matching dimensions (the inner dimensions must be equal). Notice how the code below explicitly triggers a `ValueError` because a (4x3) matrix cannot be multiplied by a (4x3) matrix.

In [16]:
matrix1 = np.matrix([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]])

matrix2 = np.matrix([
    [-1, -2, -3],
    [-4, -5, -6],
    [-7, -8, -9],
    [-10, -11, -12]])

print(matrix1.shape)
# Matrix addition
print(matrix2 + matrix1)

# Matrix multiplication - (example of not working)
# ValueError: matmul: Input operand 1 has a mismatch in its core
# dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)
print(matrix1 @ matrix2)

(4, 3)
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

### 9. Successful Matrix Multiplication
To resolve the error, we ensure dimensions align. `matrix3` is defined as a (2x3) matrix, and `matrix4` is a (3x2) matrix. Because the inner bounds match (both are 3), the `@` operator computes correctly, returning a new (2x2) matrix.

In [24]:
matrix3 = np.matrix([
    [1, 2, 3],
    [4, 5, 6],
    ])

matrix4 = np.matrix([
    [-1, -1, ],
    [-1, -1, ],
    [-1, -1, ],
    ])

print(matrix3.shape)
print(matrix4.shape)

print()
# Matrix Multiplication - working
new_matrix = matrix3 @ matrix4
print(f"Matrix multiplication: \n{matrix3} \nX\n {matrix4} \n=\n {new_matrix}\n")
print(new_matrix.shape)

(2, 3)
(3, 2)

Matrix multiplication: 
[[1 2 3]
 [4 5 6]] 
X
 [[-1 -1]
 [-1 -1]
 [-1 -1]] 
=
 [[ -6  -6]
 [-15 -15]]

(2, 2)


### 10. Defining Custom Mathematical Functions
We can use Python's `def` syntax to script our own reusable equations. Here we build implementations for basic polynomial, linear, and exponential algebraic models.

In [39]:
# Define simple functions of your own!
def g(x):
    '''
    y = x^2 (i.e. 'x-square')

    :param x:
    :return:
    '''
    return x ** 2

def f(u):
    '''
    y = 2u + 3  (i.e. 'twice u plus three')

    :param u:
    :return:
    '''
    return 2*u + 3

def h(z):
    '''
    y = e^z + 7  (i.e. 'e to the power z, plus seven')

    :param z:
    :return:
    '''
    return np.exp(z) + 7


### 11. Function Composition
With our custom formulas in place, we evaluate them sequentially. We can nest them to mimic true mathematical **Function Composition**—passing the result of one function directly inside another, like calculating $f(g(x))$.

In [40]:
# Print single values - given input x, output y:
print(g(x=3))
print(f(0))
print(h(0))
print()

# Function of Functions - fog(x) and gof(x):
print( f(g(3)) )
print( g(f(3)) )
print()

# Function of Functions - hofog(x), gofoh(x), fofof(x)
print( h(f(g(3))) )
print( g(f(h(3))) )
print( f(f(f(3))) )


9
3
8.0

21
81

1318815741.4832146
3268.531684747702
45


### 12. Vectorizing Custom Functions
Because our custom functions rely on standard math operators and NumPy utilities internally, they inherit NumPy's capabilities. We can pass a full `np.array` into our custom $g(x)$, and without altering our function, Python processes every value simultaneously.

In [41]:
# Print values of the f(x) for multipl x together, all in one!
all_X_values = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

# Calculate and Print g(x) for all values of X:
print("all_Y for g(x) = ", g(all_X_values))

# Calculate and Print f(x) for all values of X:
print("all_Y for f(x) = ", f(all_X_values))

# Calculate and Print f(x) for all values of X:
print("all_Y for h(x) = ", h(all_X_values))


all_Y for g(x) =  [  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]
all_Y for f(x) =  [ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33]
all_Y for h(x) =  [9.71828183e+00 1.43890561e+01 2.70855369e+01 6.15981500e+01
 1.55413159e+02 4.10428793e+02 1.10363316e+03 2.98795799e+03
 8.11008393e+03 2.20334658e+04 5.98811417e+04 1.62761791e+05
 4.42420392e+05 1.20261128e+06 3.26902437e+06]


### 13. Sequential Array Operations
We can build complex, data transformations quickly by feeding NumPy array results directly into other NumPy methods. Below, an array is squared, and that output is immediately passed into a division matrix.

In [44]:
# Create a 1D array of 6 elements
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)
print()

# Calculate square of all numbers in one go:
print(np.square(arr))
print()

# Calculate square of all numbers,
# followed by dividing each squared-number by 2, in one go:
print(np.divide(np.square(arr), 2))

[1 2 3 4 5 6]

[ 1  4  9 16 25 36]

[ 0.5  2.   4.5  8.  12.5 18. ]


### 14. Data Visualization with Matplotlib
This block acts as a boilerplate template for creating elegant charts using `matplotlib.pyplot`. It establishes figure sizing, overlays discrete plot points alongside continuous lines, and organizes titles, axis labels, and grids into a complete visualization payload.

In [ ]:
# A SAMPLE TEMPLATE TO PLOT SIMPLE GRAPH BETWEEN CORRESPONDING (X, Y) POINTS:
print("--- Ploy X and Y as list [six (x,y) values] ---")
x_vals = [1,2,3,4,5,6]
y_vals = [1,2,3,4,5,6] # i.e. y = x

print("--- Matplotlib: Plotting ---")
# Define the picture size
plt.figure(figsize=(10, 4))

# Plots the points (x,y) for each of the six points above
plt.scatter(x_vals, y_vals, label="GRAPH LABEL HERE", color="blue")
# Plot the graph (line joining the points)
plt.plot(x_vals, y_vals, label="GRAPH LABEL HERE", color="orange")

plt.title("=== GRAPH TITLE HERE ===")
plt.xlabel("LABEL X HERE (x)")
plt.ylabel("LABEL Y HERE (y)")
plt.legend()
# print grid
plt.grid(True)
plt.show()

--- Ploy X and Y as list [six (x,y) values] ---
--- Matplotlib: Plotting ---


## 🧮 Symbolic Mathematics with SymPy
While `numpy` and `math` are excellent for numerical calculations, `sympy` allows us to perform **symbolic algebra and calculus**. This means we can find exact algebraic derivatives and integrals rather than just estimating numerical values.

### 15. Calculating Basic Derivatives
First, we define our variables as pure `sp.Symbol` objects. After defining our variable, we can build expressions around it. Finally, we use the `sp.diff()` method to differentiate the mathematical expression with respect to our target variable.

In [3]:
# Define 'x' as a symbolic variable
x = sp.Symbol('x')

# Define a mathematical expression: y = x^2
y = x**2

# Calculate the derivative of y with respect to x
derivative_y = sp.diff(y, x)

print(f"The derivative of {y} is: {derivative_y}")

The derivative of x**2 is: 2*x


### 16. Derivatives of Advanced Functions (and Chain Rule)
SymPy includes its own symbolic versions of mathematical functions like `sp.sin()` and `sp.exp()`. Below, we use these modules to compute the precise derivatives of trigonometric and exponential functions. Notice how SymPy can automatically apply advanced calculus principles, like the **chain rule**, to highly complex expressions effortlessly.

In [4]:
# Derivative of sin(x)
trig_expr = sp.sin(x)
print(f"Derivative of {trig_expr} is: {sp.diff(trig_expr, x)}")

# Derivative of e^x
exp_expr = sp.exp(x)
print(f"Derivative of {exp_expr} is: {sp.diff(exp_expr, x)}")

# Complex expression invoking the chain rule: y = sin(x^2) + e^(2x)
complex_expr = sp.sin(x**2) + sp.exp(2*x)
print(f"\nExpression: {complex_expr}")
print(f"Calculated Derivative: {sp.diff(complex_expr, x)}")

Derivative of sin(x) is: cos(x)
Derivative of exp(x) is: exp(x)

Expression: exp(2*x) + sin(x**2)
Calculated Derivative: 2*x*cos(x**2) + 2*exp(2*x)
