In [5]:
import numpy as np

print(np)

m1 = np.matrix([
    [1, 2],
    [2, 3]
])


#np.add(np, 10)
m2 = m1 + 10
m3 = m1 * 100

print(m1)
print(m2)
print(m3)

<module 'numpy' from 'C:\\Users\\Sujeet\\AppData\\Roaming\\Python\\Python313\\site-packages\\numpy\\__init__.py'>
[[1 2]
 [2 3]]
[[11 12]
 [12 13]]
[[100 200]
 [200 300]]
