In [1]:
import numpy as np
import torch
from torch import nn, tensor, gather

In [2]:
print(np)

<module 'numpy' from 'C:\\Users\\Sujeet\\AppData\\Roaming\\Python\\Python313\\site-packages\\numpy\\__init__.py'>


In [3]:
# avoid loops
my_list = np.array(
    [1, 10, 100, 2, 20, 30, 44, 99, 32, 32]
)
print(my_list)

# advantage
print("Sum=", my_list.sum())
print("Max=", my_list.max())
print("Min=", my_list.min())
print("Avg=", my_list.mean())
print("Standard Deviation =", my_list.std())

# No loop required.
print(my_list * 100)
print(np.sin(my_list))

# sum = 0
# for element in my_list:
#     sum += element
#
# print(sum)



[  1  10 100   2  20  30  44  99  32  32]
Sum= 370
Max= 100
Min= 1
Avg= 37.0
Standard Deviation = 33.91164991562634
[  100  1000 10000   200  2000  3000  4400  9900  3200  3200]
[ 0.84147098 -0.54402111 -0.50636564  0.90929743  0.91294525 -0.98803162
  0.01770193 -0.99920683  0.55142668  0.55142668]


In [4]:
M1 = np.matrix(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

print("M1 =\n" + str(M1))
print(f"Matrix order: {M1.shape}")

# Scalar multiplication
M2 = 5 * M1
print("M2 =\n" + str(M2))

# Matrix Addition
M3 = M1 + M2
print("M3 =\n" + str(M3))

# Matrix multiplication
M4 = M1 @ M2
print("M4 =\n" + str(M4))

# Dot product
print(np.dot([1, 2, 3] , [5, 20, 35]))
print(np.dot(M1[0,:], M2[:, 0]))



M1 =
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix order: (3, 3)
M2 =
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
M3 =
[[ 6 12 18]
 [24 30 36]
 [42 48 54]]
M4 =
[[150 180 210]
 [330 405 480]
 [510 630 750]]
150
[[150]]


In [5]:
# import math
# print(math.sin(10))
# math.sin([1, 2, 3])

In [6]:
np.linalg.inv(M2)

matrix([[ 1.40737488e+14, -2.81474977e+14,  1.40737488e+14],
        [-2.81474977e+14,  5.62949953e+14, -2.81474977e+14],
        [ 1.40737488e+14, -2.81474977e+14,  1.40737488e+14]])

In [7]:
# Example of a matrix with numbers from poisson distribution
M_Randm =np.random.randint(
    low=0,
    high=10, size=(3,3)
)
print(f"Random 3x3 matrix: \n{M_Randm}")
print("----------")

# Example of a matrix with numbers from poisson distribution
M_Poiss = np.random.poisson(lam=10, size=(3,3))
print(f"3x3 matrix of Poisson Distribution: \n{M_Poiss}")

Random 3x3 matrix: 
[[6 8 8]
 [4 7 0]
 [2 2 1]]
----------
3x3 matrix of Poisson Distribution: 
[[ 9 11 10]
 [12 12 13]
 [12 10  8]]


In [8]:
print(f"A 3x3 Poisson matrix: \n{M_Poiss}")
print()

# Row-wise or Column-wise operations using axis
max_indices_in_all_cols = np.argmax(M_Poiss, axis=0, keepdims=False)
print(f"Max indices in all columns: \n{max_indices_in_all_cols}")
print(M_Poiss.max(axis=0, keepdims=True))
print()

max_indices_in_all_rows = np.argmax(M_Poiss, axis=1, keepdims=False)
print(f"Max indices in all rows: \n{max_indices_in_all_rows}")
print(M_Poiss.max(axis=1, keepdims=True))

print()
# Row-wise average:
print(f"Row-wise Average: \n{M_Poiss.mean(axis=1, keepdims=True)}")




A 3x3 Poisson matrix: 
[[ 9 11 10]
 [12 12 13]
 [12 10  8]]

Max indices in all columns: 
[1 1 1]
[[12 12 13]]

Max indices in all rows: 
[1 2 0]
[[11]
 [13]
 [12]]

Row-wise Average: 
[[10.        ]
 [12.33333333]
 [10.        ]]


In [9]:
# MAE and RMSE calculations using
## numpy (Method 1)
## Scikit-learn (Method 2)

import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Mock Data: Y (Actuals) and Y_hat (Predictions)
# Representing the housing price example (in $1000s)
Y = np.array([300, 450, 200, 600])
Y_hat = np.array([310, 430, 200, 620])

# ==========================================
# METHOD 1: Using Scikit-Learn (Recommended)
# ==========================================
mae_sklearn = mean_absolute_error(Y, Y_hat)

# Compute Mean Squared Error first, then take the square root.
# (Note: Scikit-learn 1.4+ also has a direct `root_mean_squared_error` function)
mse_sklearn = mean_squared_error(Y, Y_hat)
rmse_sklearn = np.sqrt(mse_sklearn)

print("--- Scikit-Learn Results ---")
print(f"MAE:  {mae_sklearn}")
print(f"RMSE: {rmse_sklearn:.2f}\n")


# ==========================================
# METHOD 2: Using Pure NumPy (Vectorized)
# ==========================================
# MAE: Mean of the absolute differences
mae_numpy = np.mean(np.abs(Y - Y_hat))

# RMSE: Square root of the mean of the squared differences
rmse_numpy = np.sqrt(np.mean((Y - Y_hat)**2))

print("--- NumPy Results ---")
print(f"MAE:  {mae_numpy}")
print(f"RMSE: {rmse_numpy:.2f}")

--- Scikit-Learn Results ---
MAE:  12.5
RMSE: 15.00

--- NumPy Results ---
MAE:  12.5
RMSE: 15.00


In [11]:
# Solve:
# 3x + 2y = 12
# 4x + 1y = 11

A = np.matrix([
    [3, 2],
    [4, 1],
])

B = np.matrix([
    [12, 11]
]).reshape(2, 1)

np.linalg.solve(A, B)

matrix([[2.],
        [3.]])